# CI de Nível 04 - Disparo dentro do fluxo de CI de desenvolvimento

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Testes de Unidade
        run: yarn run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Instalando Playwright
        run: yarn playwright install
      - name: Subir aplicação local
        run: yarn start &
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy da aplicação
        run: |
          # Comandos para realizar o deploy, como:
          echo "Fazendo deploy da aplicação"
          # Substitua pela lógica de deploy da sua aplicação
